apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-vs-polars
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: 662195598891.dkr.ecr.eu-west-1.amazonaws.com/hymaia/spark-vs-polars
  imagePullPolicy: Always
  mainApplicationFile: local:///app/src/spark_vs_polars/main.py
  sparkVersion: "4.1.1"

  sparkConf:
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.hadoop.fs.s3a.aws.credentials.provider: "software.amazon.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider"

  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark-jobs
    env:
      - name: INPUT_FILE
        value: "s3a://hymaia-datalake-raw/commits/data"
      - name: OUTPUT_FILE
        value: "s3a://hymaia-datalake-staging/spark-vs-polars/spark-outputs/commit"

  executor:
    cores: 1
    instances: 3
    memory: "512m"
    env:
      - name: INPUT_FILE
        value: "s3a://hymaia-datalake-raw/commits/data"
      - name: OUTPUT_FILE
        value: "s3a://hymaia-datalake-staging/spark-vs-polars/spark-outputs/commit"

  restartPolicy:
    type: Never
