apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airbyte-db-secret
  namespace: airbyte
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: airbyte-db-secret
  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: airbyte/postgresql-auth
        property: password
    - secretKey: DATABASE_USER
      remoteRef:
        key: airbyte/postgresql-auth
        property: user
