apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airbyte-db-secret
  namespace: airbyte
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: airbyte-db-secret
  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: airbyte/postgresql
        property: password
    - secretKey: DATABASE_USER
      remoteRef:
        key: airbyte/postgresql
        property: user
