# apps/dagster/external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dagster-postgresql-secret
  namespace: dagster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: dagster-postgresql-secret
  data:
    - secretKey: postgresql-password
      remoteRef:
        key: dagster/postgresql
        property: password
