apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dagster-spark-role
  namespace: spark
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications"]
    verbs: ["create", "get", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["create", "get", "watch", "delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dagster-spark-rolebinding
  namespace: spark
subjects:
  - kind: ServiceAccount
    name: dagster-code-location
    namespace: dagster
roleRef:
  kind: Role
  name: dagster-spark-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dagster-polars-role
  namespace: polars
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["create", "get", "watch", "delete", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "watch", "delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dagster-polars-rolebinding
  namespace: polars
subjects:
  - kind: ServiceAccount
    name: dagster-code-location
    namespace: dagster
roleRef:
  kind: Role
  name: dagster-polars-role
  apiGroup: rbac.authorization.k8s.io
