spark-operator:
  hook:
    upgradeCrd: true

  spark:
    jobNamespaces: ["spark"]
    serviceAccount:
      name: spark-jobs
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::662195598891:role/hyma-mds-spark-jobs"

  prometheus:
    podMonitor:
      create: true
