apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nl-query-agent-project-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hymaia/nl-query-agent
    targetRevision: env/dev
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
