apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-postgresql-secret
  namespace: mlflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mlflow-postgresql-secret
    creationPolicy: Owner
  data:
    - secretKey: postgresql-username
      remoteRef:
        key: mlflow/postgresql-auth
        property: username
    - secretKey: postgresql-password
      remoteRef:
        key: mlflow/postgresql-auth
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-admin-secret
  namespace: mlflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mlflow-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: mlflow/admin-auth
        property: username
    - secretKey: password
      remoteRef:
        key: mlflow/admin-auth
        property: password
