apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zen-ml-postgresql-secret
  namespace: zen-ml
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: zen-ml-postgresql-secret
  data:
    - secretKey: postgresql-password
      remoteRef:
        key: zen-ml/postgresql-auth
        property: password
    - secretKey: postgresql-username
      remoteRef:
        key: zen-ml/postgresql-auth
        property: username

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zenml-encryption-key-secret
  namespace: zen-ml
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: zenml-encryption-key-secret
  data:
    - secretKey: encryption-key
      remoteRef:
        key: zen-ml/encryption-key
