apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccountPipelineName }}
  namespace: zen-ml
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.global.roleIamPipeline }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zenml-pipeline-role
  namespace: zen-ml
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
  - apiGroups: ["events"]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zenml-pipeline-rolebinding
  namespace: zen-ml
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.serviceAccountPipelineName }}
    namespace: zen-ml
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: zenml-pipeline-role
