apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metabase-postgresql-secret
  namespace: metabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: metabase-postgresql-secret
  data:
    - secretKey: postgresql-password
      remoteRef:
        key: metabase/postgresql
        property: password
    - secretKey: postgresql-username
      remoteRef:
        key: metabase/postgresql
        property: username
