# generated by terraform from infra/templates/airbyte-values.yaml.tpl

global:
  airbyteUrl: "https://airbyte.fcussac.app.hymaia.com"
  serviceAccountName: airbyte-admin

  storage:
    type: s3
    s3:
      region: eu-west-1
      authenticationType: instanceProfile
    bucket:
      log: hymaia-airbyte-storage
      auditLogging: hymaia-airbyte-storage
      state: hymaia-airbyte-storage
      workloadOutput: hymaia-airbyte-storage
      activityPayload: hymaia-airbyte-storage

  database:
    type: external
    host: "${rds_endpoint}"
    port: 5432
    name: "airbyte"
    user: "airbyte"
    secretName: "airbyte-db-secret"
    passwordSecretKey: "DATABASE_PASSWORD"

  auth:
    enabled: true
    instanceAdmin:
      firstName: "Franck"
      lastName: "Cussac"

airbyte:
  postgresql:
    enabled: false

  minio:
    enabled: false

  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "${role_iam_arn}"

  ingress:
    enabled: true
    className: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/certificate-arn: "${certificate_arn}"
      alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600
    hosts:
      - host: airbyte.fcussac.app.hymaia.com
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend: server
