# generated by terraform from infra/templates/dagster-values.yaml.tpl

dagster:
  postgresql:
    enabled: false
    postgresqlHost: "${rds_endpoint}"
    postgresqlUsername: "dagster"
    postgresqlDatabase: "dagster"

  dagster-user-deployments:
    deployments:
      - name: "discover-dagster"
        image:
          repository: "${ecr_user_code}"
          tag: "latest"
          pullPolicy: Always
        dagsterApiGrpcArgs:
          - "-m"
          - "discover_dagster.definitions"
        port: 3030

  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/certificate-arn: "${certificate_arn}"
    dagsterWebserver:
      host: dagster.fcussac.app.hymaia.com

global:
  postgresqlSecretName: "dagster-postgresql-secret"
