# generated by terraform from infra/templates/dagster-values.yaml.tpl

dagster:
  postgresql:
    enabled: false
    postgresqlHost: "${rds_endpoint}"
    postgresqlUsername: "dagster"
    postgresqlDatabase: "dagster"

  serviceAccount:
    create: false
    name: "dagster-code-location"

  dagster-user-deployments:
    deployments:
      - name: "orchestration-dagster"
        image:
          repository: "${ecr_user_code}"
          tag: "latest"
          pullPolicy: Always
        dagsterApiGrpcArgs:
          - "-m"
          - "orchestration_dagster.definitions"
        port: 3030
      - name: "github-dbt-project"
        image:
          repository: "${dagster_user_code_github_dbt}"
          tag: "latest"
          pullPolicy: Always
        dagsterApiGrpcArgs:
          - "-m"
          - "dagster_defs.definitions"
        port: 3031

  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/certificate-arn: "${certificate_arn}"
    dagsterWebserver:
      host: dagster.fcussac.app.hymaia.com

global:
  postgresqlSecretName: "dagster-postgresql-secret"
  serviceAccountName: "dagster-code-location"
  roleIamDagster: "${role_iam_dagster}"
  roleIamPolars: "${role_iam_polars}"
