# generated by terraform from infra/templates/metabase-values.yaml.tpl

metabase:
  database:
    type: "postgres"
    host: "${rds_endpoint}"
    port: 5432
    dbname: "metabase"
    existingSecret: "metabase-postgresql-secret"
    existingSecretUsernameKey: "postgresql-username"
    existingSecretPasswordKey: "postgresql-password"

  ingress:
    enabled: true
    className: "alb"
    hosts:
      - "metabase.fcussac.app.hymaia.com"
    path: /*
    pathType: ImplementationSpecific
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/certificate-arn: "${certificate_arn}"

  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "${role_iam_arn}"
