# generated by terraform from infra/templates/mlflow-values.yaml.tpl

mlflow:
  backendStore:
    databaseMigration: true
    databaseConnectionCheck: true
    postgres:
      enabled: true
      host: "${rds_endpoint}"
      port: 5432
      database: "mlflow"
    existingDatabaseSecret:
      name: "mlflow-postgresql-secret"
      usernameKey: "postgresql-username"
      passwordKey: "postgresql-password"

  auth:
    enabled: true
    adminUsername: "admin"
    adminPassword: ""
    existingAdminSecret:
      name: "mlflow-admin-secret"
      usernameKey: "username"
      passwordKey: "password"

  extraArgs:
    allowedHosts: "mlflow.fcussac.app.hymaia.com"
    uvicornOpts: "--log-level info"

  log:
    enabled: false

  extraEnvVars:
    MLFLOW_ALLOW_HOSTS: "mlflow.fcussac.app.hymaia.com"
    MLFLOW_TRACKING_USERNAME:
      valueFrom:
        secretKeyRef:
          name: mlflow-postgresql-secret
          key: postgresql-username
    MLFLOW_BACKEND_STORE_URI_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: mlflow-postgresql-secret
          key: postgresql-password

  artifactRoot:
    s3:
      enabled: true
      bucket: "${artifact_bucket}"

  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "${role_iam_arn}"

  ingress:
    enabled: true
    className: "alb"
    hosts:
      - host: "mlflow.fcussac.app.hymaia.com"
        paths:
          - path: /*
            pathType: ImplementationSpecific
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/certificate-arn: "${certificate_arn}"
