# generated by terraform from infra/templates/zen-ml-values.yaml.tpl

zenml:
  server:
    serverURL: "https://zenml.fcussac.app.hymaia.com"
    dashboardURL: "https://zenml.fcussac.app.hymaia.com"

    database:
      url: "mysql://${rds_username}@${rds_endpoint}:3306/zenml"
      passwordSecretRef:
        name: "zen-ml-postgresql-secret"
        key: "postgresql-password"

    environmentSecretKeyRefs:
      - name: ZENML_SECRETS_STORE_ENCRYPTION_KEY
        secretName: "zenml-encryption-key-secret"
        secretKey: "encryption-key"

    ingress:
      enabled: true
      className: "alb"
      annotations:
        alb.ingress.kubernetes.io/group.name: shared-alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
        alb.ingress.kubernetes.io/certificate-arn: "${certificate_arn}"
      host: "zenml.fcussac.app.hymaia.com"
      path: /
      tls:
        enabled: false

  serviceAccount:
    create: true
    name: "zenml-sa"
    annotations:
      eks.amazonaws.com/role-arn: "${role_iam_arn}"

global:
  serviceAccountPipelineName: "zenml-pipeline"
  roleIamPipeline: "${role_iam_pipeline_arn}"
